### ISSUE TITLE
shorter IE syntax and old IE supoprt

### ISSUE THREAD

**Issue by stoyan** [suitcss/rework-suit#2]
``` css
.stuffs {
  -ms-filter: "alpha(opacity=50)";
  filter: alpha(opacity=50);
}
```
